### ISSUE TITLE
Support large int values on arm systems

### ISSUE THREAD

**Issue by yob** [dim13/unifi#19]
I tested a program on my amd64 linux machine, then cross compiled it for a raspberry pi like this:

```
GOOS=linux GOARCH=arm GOARM=7 go build -o foo .
```

When I ran it on the pi4, the process failed because the Sta tx_bytes field overflowed the int size:

```go
stations, err := u.Sta(site)                                                                                                                                                                             
if err != nil {
     log.Fatalf("ERROR: %v\n", err)
}
```

output:
```
2021/05/01 22:12:45 ERROR: json: cannot unmarshal number 3753204908 into Go struct field Sta.Data.tx_bytes of type int
```

I found this commit in a fork resolves the issue for me: https://github.com/mbee/unifi/commit/a1f8d620af6305dd1bfb38f76d05e48886835e79

**Comment by dim13** [comment]
Thanks, I've cherry-picked this commit and fixed some usage of those fields.

**Comment by dim13** [comment]
Gonna close this issue then.
